### PR TITLE
roll up of all open PRs, plus 2 fixes

### LINKED ISSUE #11: clean --egg misses .eggs (plural)
Eggs downloaded via `setup_requires=...` are put in `.eggs` not `.egg` and `python setup.py clean --eggs` misses them.

(sidebar: setup_requires isn't necessary post PEP-518 and pip >v10)

### PR DESCRIPTION
**Pull request by maphew**
This pull request incorporates  PR #8, #9, #10, #13 and closes #11 and #12

- fix setupext namespace collision
- typo in readme usage notes for `--eggs`
- shield.io instead pyp.in for badges
- also catch and remove `.eggs` folder
- Early exit on Windows because distutils tries to something with RPM

### CODE REVIEW

**Comment by maphew** [comment]
Eeep. Travis failed because I used the newer  py3.6 `f'...'` print() syntax instead of `'...'.format()`. I'll fix that.

**Comment by maphew** [comment]
@dave-shawley I'm happy to help with maintenance of this module. (It would be good to get a current version on Pypi.)

**Comment by dave-shawley** [comment]
@maphew I have no clue how I missed this activity.  It must have gotten lost in the inbox altogether.  I did notice the direct mentions from you and @cmarquardt this morning.  Sounds like I need to check my GitHub notification settings.  I am very sorry about letting this languish.  It never caught on at work so I haven't been using it.  I'll review the rolled up PR and see what is left afterwards.

To @maphew , @cmarquardt, @ionelmc, @kotfu and anyone else that I've ignored, I'm sorry about that.  I really do appreciate the assistance.

**Comment by maphew** [comment]
Well, I'm glad now I took the chance of being annoying and sent another
e-poke :) Thanks Dave

**Comment by maphew** [comment]
@dave-shawley now that the PR has been merged, it's safe for me to delete my fork right? I don't need it anymore but I don't want to mess anyone else up.

**Comment by dave-shawley** [comment]
> @dave-shawley now that the PR has been merged, it's safe for me to delete my fork right? I don't need it anymore but I don't want to mess anyone else up.

@maphew yup.  You should be good.  Lemme know if you run into any other issues.

**Pull request merged**
